### PR TITLE
Update repository and ebuild for latest VMWare version

### PR DESCRIPTION
**Pull request by BtbN**

### CODE REVIEW

**Comment by gmt** [comment]
Hey, thanks.  So... this code works for you?  Looks perfectly fine, although I can't test it extensively as I'm trying to break my vmware desktop products habit... Do you use systemd or openrc, out of curiosity?

**Comment by BtbN** [comment]
I'm using it on my headless server with openrc, with the server useflag enabled. Works fine.
On my laptop i'm using it with systemd, without hostd though. Works also fine.

**Comment by gmt** [comment]
OK, mostly works for me but I get this:
Hostd[21683]: error: N7Vmacore21NumberFormatExceptionE(Config Value not a boolean)
 Hostd[21683]: backtrace[00] rip 00007fb61ab2a4f4 Vmacore::System::Stacktrace::CaptureWork(unsigned int)
backtrace[01] rip 00007fb61a92b837 Vmacore::System::SystemFactoryImpl::CreateQuickBacktrace(Vmacore::Ref<Vmacore::System::Backtrace>&)
backtrace[02] rip 00007fb61a8d482d Vmacore::Throwable::Throwable(std::string const&)
backtrace[03] rip 00007fb61a8cb319 /opt/vmware/lib/vmware/lib/libvmacore.so/libvmacore.so(+0x17b319) [0x7fb61a8cb319]
Hostd[21683]: backtrace[04] rip 00007fb61cae968a /opt/vmware/lib/vmware/bin/vmware-hostd(+0xd1168a) [0x7fb61cae968a]
.
.
.
Hostd[21683]: backtrace[10] rip 00007fb614cbff90 /lib64/libc.so.6(__libc_start_main+0xf0) [0x7fb614cbff90]

But who knows maybe that will be fixed when I reboot or something.  Often ime such wackiness has to do with vmware not correctly pulling in its silly pile of private libraries.

**Comment by gmt** [comment]
> Often ime such wackiness has to do with vmware not correctly pulling in its silly pile of private libraries.

or not running ubuntu, depending on how you look at it.... :)

**Comment by BtbN** [comment]
Oh, i completely forgot about that one. It's not a library issue, it's just vmwares lovely way of telling you about a syntax error in config.xml.

In /etc/vmware/hostd/config.xml, replace <enabled>##{USE_STATSSVC}##</enabled> with <enabled>false</enabled> (or true, no idea what statssvc does, I disabled it).

**Comment by gmt** [comment]
On Sun, Feb 22, 2015 at 6:18 AM, BtbN <notifications@github.com> wrote:

> vmwares lovely way of telling you about a syntax error in config.xml.


Lovely indeed!  Somehow they get systemd-journald to flood my KDE
notification thingy and all of my consoles, complete with audio feedback,
its like /usr/bin/write on steriods.  Thanks again, everything seems to be
good now (although I also haven't actually tested hostd, even in  the old
versions I used to actually use).

**Pull request merged**
